In [1]:
import os
import sys
from pathlib import Path

# Change to project root (parent of notebooks/)
notebook_dir = Path.cwd()
project_root = notebook_dir.parent
os.chdir(project_root)
sys.path.insert(0, str(project_root))  # For imports from pokeml/


print(f'PYTHONPATH added: {project_root}') # Verify: /path/to/project_root

# Load the minimal_pkdx
import pandas as pd
df = pd.read_csv('datasets/pkdx_min.csv')

PYTHONPATH added: /Users/pano/Library/Mobile Documents/com~apple~CloudDocs/coding/portfolio/ml_pokemon

In [2]:
from pokeml.features.preprocess import prepare_data_predict
from pokeml.models.predict import predict_stats

new_pokes = prepare_data_predict('datasets/new_pokes.csv')
predict_stats(input_model='2026_04_15_w_stop_cat_native',
                  new_poke_data=new_pokes,
                  output_preds='test_easy_cat_native_preds')

     name  pred_bst  uncertainty pred_bst_text       model
0   Browt       283           13      283 ± 13  cat_native
1  Pombon       302            0       302 ± 0  cat_native
2  Gecqua       297            1       297 ± 1  cat_native

In [ ]:
from pokeml.models.predict import predict_all_models


predict_all_models(run='2026_04_15_w_stop',
                   new_poke_data=new_pokes,
                   output_preds='2026_04_14_w_stop_all')

name            Browt    Pombon    Gecqua
cat_native   283 ± 13   302 ± 0   297 ± 1
cat_ordinal  282 ± 12   294 ± 1   289 ± 3
light_gbm    270 ± 52  305 ± 17  292 ± 27